Simplify autopkgtest 'smoke' to be easier to debug
Simplify Debian autopkgtest RocksDB part and make it more verbose so that
future regressions like this are easier to debug.

Also remove QUIET from the RocksDB FIND_PACKAGE call so that it is easier
to read in build logs what libraries were detected. Also add missing
underscores to error messages.

# Conflicts:
#	debian/tests/smoke

diff --git a/debian/tests/smoke b/debian/tests/smoke
--- a/debian/tests/smoke
+++ b/debian/tests/smoke
@@ -1,6 +1,4 @@
 #!/bin/sh
-set -ex
-
 # dep8 smoke test for mysql-server
 # Author: Robie Basak <robie.basak at canonical.com>
 #
@@ -23,7 +21,10 @@ set -ex
 #
 # 3) Checks compression support for InnoDB & RocksDB engine.
 
-# Start the deamon if it was not running. For example in Docker testing
+echo "Running test 'smoke'"
+set -ex
+
+# Start the daemon if it was not running. For example in Docker testing
 # environments there might not be any systemd et al and the service needs to
 # be started manually.
 if ! which systemctl
@@ -50,7 +51,7 @@ CREATE TABLE foo (bar INTEGER);
 INSERT INTO foo (bar) VALUES (41);
 EOT
 
-result=`echo 'SELECT bar+1 FROM foo;'|mysql --batch --skip-column-names --user=testuser --password=testpassword testdatabase`
+result=$(echo 'SELECT bar+1 FROM foo;'|mysql --batch --skip-column-names --user=testuser --password=testpassword testdatabase)
 if [ "$result" != "42" ]; then
        echo "Unexpected result" >&2
        exit 1
@@ -65,17 +66,24 @@ DROP DATABASE testdatabase;
 DROP USER 'testuser'@'localhost';
 EOT
 
-mysql <<EOT
+# List based on what is advertised at
+# https://mariadb.com/kb/en/innodb-page-compression/#configuring-the-innodb-page-compression-algorithm
+# but disabled  with '#' the options that are not available in this binary build
+mariadb <<EOT
 SET GLOBAL innodb_compression_algorithm=lz4;
+#SET GLOBAL innodb_compression_algorithm=lzo;
+#SET GLOBAL innodb_compression_algorithm=lzma;
+#SET GLOBAL innodb_compression_algorithm=bzip2;
 SET GLOBAL innodb_compression_algorithm=snappy;
 SET GLOBAL innodb_compression_algorithm=zlib;
 SET GLOBAL innodb_compression_algorithm=none;
 EOT
 
-# Check whether RocksDB should be installed or not.
+# Check whether RocksDB should be installed or not
 plugin=mariadb-plugin-rocksdb
-if [ "`dpkg-architecture -qDEB_HOST_ARCH_BITS`" != 32 ] &&
-   [ "`dpkg-architecture -qDEB_HOST_ARCH_ENDIAN`" = little ]; then
+if [ "$(dpkg-architecture -qDEB_HOST_ARCH_BITS)" != 32 ] &&
+   [ "$(dpkg-architecture -qDEB_HOST_ARCH_ENDIAN)" = little ]
+  then
   dpkg-query -W $plugin
 
   LOG=/var/lib/mysql/#rocksdb/LOG
@@ -83,8 +91,18 @@ if [ "`dpkg-architecture -qDEB_HOST_ARCH_BITS`" != 32 ] &&
   #      mariadb-server-10.3, which happens before that of the plugin.
   [ -e $LOG ] || mysql -e "INSTALL PLUGIN RocksDB SONAME 'ha_rocksdb';"
   # XXX: rocksdb_supported_compression_types variable does not report ZSTD.
+
+  # Print RocksDB supported items so test log is easier to debug
+  grep -F " supported:" $LOG
+
+  # Check that the expected compression methods are supported
   for a in LZ4 Snappy Zlib ZSTD; do
-    grep -qE "k$a(Compression)? supported: 1" $LOG
+    if ! grep -qE "k$a(Compression)? supported: 1" $LOG
+    then
+      # Fail with explicit error message
+      echo "Error: Compression method $a not supported by RocksDB!" >&2
+      exit 1
+    fi
   done
 else
   ! dpkg-query -W $plugin
